### ISSUE TITLE
Problem with Python AlphaZero using Keras 3.1.1

### ISSUE THREAD

**Issue by lanctot** [google-deepmind/open_spiel#1206]
Using Ubuntu 24.04 and Python 3.12, it seems like `model_test.py` is failing using Keras 3.1.1:

```
(venv) lanctot@nitro-exp:~/open_spiel/open_spiel/python/algorithms/alpha_zero$ python model_test.py 
             .
             .
             .
[       OK ] ModelTest.test_model_learns_simple0 ('mlp')
[ RUN      ] ModelTest.test_model_learns_simple1 ('conv2d')
[  FAILED  ] ModelTest.test_model_learns_simple1 ('conv2d')
[ RUN      ] ModelTest.test_model_learns_simple2 ('resnet')
[  FAILED  ] ModelTest.test_model_learns_simple2 ('resnet')
======================================================================
ERROR: test_model_learns_optimal1 ('conv2d') (__main__.ModelTest)
ModelTest.test_model_learns_optimal1 ('conv2d')
test_model_learns_optimal('conv2d')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lanctot/venv/lib/python3.12/site-packages/absl/testing/parameterized.py", line 322, in bound_param_test
    return test_method(self, testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 101, in test_model_learns_optimal
    model = build_model(game, model_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 50, in build_model
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 173, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 235, in _define_graph
    torso = cascade(torso, [
            ^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 28, in cascade
    x = fn(x)
        ^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 50, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/lanctot/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lanctot/venv/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1440, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

======================================================================
ERROR: test_model_learns_optimal2 ('resnet') (__main__.ModelTest)
ModelTest.test_model_learns_optimal2 ('resnet')
test_model_learns_optimal('resnet')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lanctot/venv/lib/python3.12/site-packages/absl/testing/parameterized.py", line 322, in bound_param_test
    return test_method(self, testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 101, in test_model_learns_optimal
    model = build_model(game, model_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 50, in build_model
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 173, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 241, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 28, in cascade
    x = fn(x)
        ^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 50, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/lanctot/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lanctot/venv/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1440, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

======================================================================
ERROR: test_model_learns_simple1 ('conv2d') (__main__.ModelTest)
ModelTest.test_model_learns_simple1 ('conv2d')
test_model_learns_simple('conv2d')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lanctot/venv/lib/python3.12/site-packages/absl/testing/parameterized.py", line 322, in bound_param_test
    return test_method(self, testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 60, in test_model_learns_simple
    model = build_model(game, model_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 50, in build_model
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 173, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 235, in _define_graph
    torso = cascade(torso, [
            ^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 28, in cascade
    x = fn(x)
        ^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 50, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/lanctot/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lanctot/venv/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1440, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

======================================================================
ERROR: test_model_learns_simple2 ('resnet') (__main__.ModelTest)
ModelTest.test_model_learns_simple2 ('resnet')
test_model_learns_simple('resnet')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lanctot/venv/lib/python3.12/site-packages/absl/testing/parameterized.py", line 322, in bound_param_test
    return test_method(self, testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 60, in test_model_learns_simple
    model = build_model(game, model_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model_test.py", line 50, in build_model
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 173, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 241, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 28, in cascade
    x = fn(x)
        ^^^^^
  File "/home/lanctot/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 50, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/lanctot/venv/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/lanctot/venv/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1440, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

----------------------------------------------------------------------
Ran 6 tests in 3.435s

FAILED (errors=4)
(venv) lanctot@nitro-exp:~/open_spiel/open_spiel/python/algorithms/alpha_zero$ 
```

**Comment by lanctot** [comment]
Tagging original author @tewalds, but we could use some help to port these algorithms to the new Keras version.

**Comment by DaanS8** [comment]
Had the same issue, solved it by replacing the function `batch_norm ` in `open_spiel/python/algorithms/alpha_zero/model.py` with:

```
def batch_norm(training, updates, name):
    def batch_norm_layer(x):
        bn = tfkl.BatchNormalization(name=name, trainable=True)
        return bn(x)
    return batch_norm_layer
```

I am far from an expert on this topic, and this code was suggested by GenAI. 
Use with caution. Hopefully this helps with solving the issue.

**Comment by lanctot** [comment]
Interesting... Thanks! I will check this with the experts on my side 😅

**Comment by tacertain** [comment]
Been trying to puzzle through this as it's also blocking me. The error referenced above I believe is because the value of the training variable is a TF placeholder, so a Tensor, and Keras is expecting it to be a python bool. So by not passing it in the replacement code above, you don't have that problem. However, unless there's magic going on to handle whether it's in training or inference mode, I don't think you're going to get the same results. Note the warning in the comments of `batch_norm`:

```
    # This emits a warning that training is a placeholder instead of a concrete
    # bool, but seems to work anyway.
```

I think the warning is now an error.

Secondarily, there's no updates method on layers any more. I can't even find where that used to be a valid method. Unfortunately, "updates" is not a very precise term for searching.

All I know about Keras I've learned in the past few hours, but my fear at this point is that the current code is based on TF v1 and Keras v1 and there are major changes that will need to be made to bring it up-to-date (and the AI-suggested code is valid code but doesn't capture all the functionality needed for alpha_zero). Hopefully I'm wrong, but I don't think I'm going to try to make any more progress without some more insight.

**Comment by tacertain** [comment]
@lanctot I have been working on changing alpha_zero.py into Keras 3 code, and leaving it as backend-agnostic as possible (i.e. using as few TF-specific calls as possible). I think that I'm close, but am running into the python-greedy-import problem as reflected in #1122. How worthwhile is this work? I've gotten I think all the learning I'm going to get out of the coding part - I just want something that runs AlphaZero now. Should I just use the C++ version? I can keep trying to get the python version to work in Keras 3, but does anybody but me really care? Also, if I do want to get it done for v1.5, what's the deadline?

**Comment by lanctot** [comment]
@tacertain A working Python implementation of AlphaZero is something we will certainly figure out a way to keep in the long-run. It's definitely not going away.. as in: we won't remove it. It serves as a very good user-friendly first look at AlphaZero and is highly valuable for that reason. 

Right now, Keras 3 is still kinda new, most people are not even using Python 3.12 yet so I don't think Keras 3 is default-installed anywhere (or if so, it's very recent...) so this is on the low end of the current priority list. If Keras is causing problems specifically, we could simply just move to Pytorch or TF2. I'd prefer to keep with Keras if possible.

That said, it really is intended for a first-time user or tinkerer and does not scale as well as the LibTorch-based C++ implementation (or distributed ones found in other frameworks like RLLib or muzero-general -- which still support OpenSpiel games). So to your question of which one to use -- if you're comfortable with C++ and PyTorch, I'd say use that as it's more scalable. But it is also single-machine, so that will be a limitation for larger games. 

On v1.5, that depends on what my schedule looks like. I was hoping to release before mid-June, but most of what I wanted to get in is there already.. just a few last minute larger PRs that have been in the queue for some time (including your Quoridor fixes). I'm not expecting any of these known issues with Keras 3 to get fixed by then.. it's too soon and there's not enough wide use of Python 3.12 / Keras 3 yet to warrant all the effort right now. I put warnings in those files to warn users that there are problems with pointers to these threads. I did that with the longer-term goal of fixing (or removing) them by next release. But of course, if they managed to get fixed before then, great, we'll include them 👍

**Comment by encratite** [comment]
Just ran into the same issue after setting up TensorFlow in WSL 2, trying to run the AlphaZero sample:
```(open_spiel) void@PLEROMA:~/data/open_spiel/open_spiel/python/examples$ python alpha_zero.py
2025-02-14 19:34:01.896621: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1739558041.909525    2781 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739558041.913590    2781 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-14 19:34:01.926213: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py:27: UserWarning: Python AlphaZero has known issues when using Keras 3 and may be removed in a future version unless fixed. See OpenSpiel github issue #1206 for details.
  warnings.warn(
Starting game connect_four
Writing logs and checkpoints to: /tmp/az-2025-02-14-19-34-connect_four-l7v2hz_q
Model type: resnet(128, 10)
actor-0 started
actor-1 started
learner started
[2025-02-14 19:34:05.774] Initializing model
evaluator-0 started
Exception caught in actor-1: as_list() is not defined on an unknown TensorShape.
Exception caught in evaluator-0: as_list() is not defined on an unknown TensorShape.
actor-1 exiting
[2025-02-14 19:34:05.815]
===================== Exception caught =====================
Traceback (most recent call last):
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 171, in _watcher
    return fn(config=config, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 331, in learner
    model = _init_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 148, in _init_model_from_config
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 181, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 249, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 36, in cascade
    x = fn(x)
        ^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 58, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1441, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.

============================================================evaluator-0 exiting

Exception caught in learner: as_list() is not defined on an unknown TensorShape.
Exception caught in actor-0: as_list() is not defined on an unknown TensorShape.
[2025-02-14 19:34:05.815] learner exiting
learner exiting
actor-0 exiting
Process Process-2:
Process Process-3:
Process Process-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 171, in _watcher
    return fn(config=config, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 171, in _watcher
    return fn(config=config, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 268, in actor
    model = _init_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 287, in evaluator
    model = _init_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 148, in _init_model_from_config
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 148, in _init_model_from_config
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 181, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 181, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 249, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 249, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 36, in cascade
    x = fn(x)
        ^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 36, in cascade
    x = fn(x)
        ^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 171, in _watcher
    return fn(config=config, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 58, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 58, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 268, in actor
    model = _init_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1441, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1441, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 148, in _init_model_from_config
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: as_list() is not defined on an unknown TensorShape.
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 181, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
ValueError: as_list() is not defined on an unknown TensorShape.
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 249, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 36, in cascade
    x = fn(x)
        ^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 58, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1441, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.
Traceback (most recent call last):
  File "/home/void/data/open_spiel/open_spiel/python/examples/alpha_zero.py", line 98, in <module>
    app.run(main)
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
             ^^^^^^^^^^
  File "/home/void/data/open_spiel/open_spiel/python/examples/alpha_zero.py", line 93, in main
    alpha_zero.alpha_zero(config)
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 545, in alpha_zero
    learner(game=game, config=config, actors=actors,  # pylint: disable=missing-kwoa
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 171, in _watcher
    return fn(config=config, logger=logger, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 331, in learner
    model = _init_model_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 148, in _init_model_from_config
    return model_lib.Model.build_model(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 181, in build_model
    cls._define_graph(model_type, input_shape, output_size, nn_width,
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 249, in _define_graph
    torso = cascade(observations, [
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 36, in cascade
    x = fn(x)
        ^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/open_spiel/python/algorithms/alpha_zero/model.py", line 58, in batch_norm_layer
    applied = bn(x, training)
              ^^^^^^^^^^^^^^^
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/void/venv/open_spiel/lib/python3.12/site-packages/tensorflow/python/framework/tensor_shape.py", line 1441, in as_list
    raise ValueError("as_list() is not defined on an unknown TensorShape.")
ValueError: as_list() is not defined on an unknown TensorShape.```

**Comment by lanctot** [comment]
Closing this issue as we no longer support Tensorflow.

Efforts are now in place to port this code to JAX: https://github.com/google-deepmind/open_spiel/pull/1362
